### PR TITLE
[New Util] Death Call and [New Unit] Thicc tank that is big, and explodes upon death. (Wants to be merged)

### PR DESCRIPTION
**Pull request by Lomiaya**
Support for death call(亡语) (Use by reloading Unit::DeathCall)。
Adds THICC TANK, which explodes upon death.

### CODE REVIEW

**Comment by Lomiaya** [comment]
(As referred in #267 .) 
Do think the new Utility may come in handy.

**Review by LazyJazz — APPROVED** [review]
LGTM!

**Comment by Lomiaya** [comment]
Resolves the conflict in "selectable units" file manually. Changes nearly nothing in practical (other than the place sequence of units in the selectable tab).

**Review by qinchuanhui — APPROVED** [review]
LGTM, you can get the corresponding score.

**Comment by qinchuanhui** [comment]
Good job. I will just close this PR, and if u want to merge it, just contact us after the project-deadline

**Pull request closed without merging**
