### PR TITLE
[Bullet] Mine

### PR DESCRIPTION
**Pull request by EDGE-qy**
w.r.t. #87

### CODE REVIEW

**Comment by EDGE-qy** [comment]
Labor:
EDGE-qy for Mine the Bullet, some debugging
JasonL for MineSampleTank the Unit

**Review by LazyJazz — DISMISSED** [review]
LGTM!

**Comment by LazyJazz** [comment]
Just fix the conflicts before merge

**Comment by EDGE-qy** [comment]
> Just fix the conflicts before merge

Conflict fixed

**Review by LazyJazz — APPROVED** [review]
LGTM! Call me in wechat if you want to merge your contribution into the main branch.

**Pull request merged**
