### PR TITLE
[New Unit] Three Body Man

### PR DESCRIPTION
**Pull request by EDGE-qy**
This serves as the TASK 2 of my Homework

And my Issue about this would be closed then

### CODE REVIEW

**Review by wanghao-create — COMMENTED** [review]
相比tiny_tank没有改动的方法可以直接继承。IsHit()需要修改。

**Comment by EDGE-qy** [comment]
> 相比tiny_tank没有改动的方法可以直接继承。IsHit()需要修改。

谢谢学长！isHit()经过修改已经细化了碰撞体积，类继承的话我看继承关系不太多就没改（懒惰ww）

**Comment by EDGE-qy** [comment]
泪目，终于跑过autocheck了

**Review by LazyJazz — DISMISSED** [review]
Excellent job

**Comment by LazyJazz** [comment]
You need to resolve those conflicts first before merging.

**Comment by EDGE-qy** [comment]
> You need to resolve those conflicts first before merging.

Conflicts are resolved and it seems that a second approval is needed

**Pull request merged**
