### PR TITLE
[Bug] Fix rocket display error

### PR DESCRIPTION
**Pull request by XuGW-Kevin**
如题，修复了火箭弹的颜色显示bug. #196

### CODE REVIEW

**Comment by ljc1301** [comment]
I think it's better to use
```cpp
SetColor(glm::vec4{1.0f, 1.0f, 1.0f, 1.0f});
```
Later I will open another issue to emphasis this bug.

**Comment by XuGW-Kevin** [comment]
Thanks. I will check this later.

**Comment by XuGW-Kevin** [comment]
Fixed. Thanks very much.

**Review by LazyJazz — APPROVED** [review]
LGTM!

**Pull request merged**
