### PR TITLE
In fact, I haven't change anything

### PR DESCRIPTION
**Pull request by zcszcs522**

### CODE REVIEW

**Comment by zcszcs522** [comment]
"This branch has conflicts that must be resolved", how can this problem be dealt with

**Comment by zcszcs522** [comment]
battle_game luck

**Comment by zcszcs522** [comment]
we don't give information about where the good luck or bad luck is, everything is decided by luck

**Review by zcszcs522 — COMMENTED** [review]
actions fixed

**Review by LazyJazz — APPROVED** [review]
LGTM!

**Comment by LazyJazz** [comment]
Call me in wechat if you want to merge your contribution into the main branch.

**Comment by LazyJazz** [comment]
Nonono, you should commit your new changes into a new branch and then open a new pr.
Continue committing on this pr will cancel your approved state. Which could make you lose scores.

**Comment by zcszcs522** [comment]
Excuse me, I have an additional question. Can I do something to delete the wrong commitment, or could the previous commit just be added into the main fork?

2023-01-12 22:35:54 "LazyJazz" ***@***.***> 写道：

Nonono, you should commit your new changes into a new branch and then open a new pr.
Continue committing on this pr will cancel your approved state. Which could make you lose scores.

**Comment by qinchuanhui** [comment]
I just close it, u can feel free to reopen it if u want

**Pull request closed without merging**
